name: tf29_se_voicebank_macos
channels:
  - defaults
dependencies:
  - python=3.8
  - pip=22.1.2=py38*
  - pip:
    - matplotlib==3.5.3
    - musdb==0.4.0
    - museval==0.4.0
    - numpy==1.22.3
    - pesq==0.0.4
    - pypesq==1.2.4
    - pystoi==0.3.3
    - pyyaml==6.0
    - resampy==0.3.0
    - scipy==1.8.1
    - sounddevice==0.4.5
    - soundfile==0.11.0
    - tqdm==4.64.0
    - tensorflow-metal==0.5.0 
    - tensorflow-macos== 2.9.2
    - tensorboard==2.9.1
    - librosa==0.9.2
    - ipykernel==6.15.0
