default:
  - _self_
  - dset: VoiceBankDEMAND

dummy:
dset:
  wav: "./data/VoiceBankDEMAND/DS_10283_2791"
  split: 0.9
  sample_rate: 16000
  # segment: 1.008
  segment: 1.024 # unet
  # segment: 4
  # lstm model
  n_fft: 512
  win_length: 512
  hop_length: 256
  # hop_length: 128
  # n_fft: 256
  # win_length: 256
  # hop_length: 128
  # hop_length: 64
  channels: 1
  top_db: 100
  # fft: True
  fft: False
  center: True
  save_path: "./data/preprocess"
  # normalize: 'none'
  # normalize: 'min-max'
  normalize: 'z-score'
  # segment_normalization: True # if this paramter is not existed, then default is False
  segment_normalization: False 

model:
  # name: 'rnn'
  # name: 'lstm'
  # name: 'gru'
  # name: 'crn'
  name: 'unet'
  # name: 'conv-tasnet'
  lstm_layer: 256 # recurret type nlayer
  # lstm_layer: 128
  n_feature: 257
  n_segment: 64 # 1.008 sec in 512 window, 256 hop, sr = 16000 Hz
  # n_segment: 127 # 1.008 sec in 512 window, 128 hop, sr = 16000 Hz
  # n_feature: 129
  # n_segment: 127 # 1.008 sec in 256 window, 128 hop, sr = 16000 Hz
  # n_segment: 253 # 1.008 sec in 256 window, 64 hop, sr = 16000 Hz
  n_mels: 128
  f_min: 125
  f_max: 8000
  fft_normalization: True # False
  metric: ['sisdr', ] # 'nb-pesq', 'sdr', 'stoi', 'wb-pesq', 
  path: 
  ckpt:

test:
  steps: 1
  wav: "./data/VoiceBankDEMAND/DS_10283_2791"
  save: False

tflite: 
  format: 'float32'
  test: True


optim:
  load: False
  optim: 'adam'
  lr: 0.0003
  # optim: 'sgd'
  # lr: 0.001
  loss: 'mse'
  # loss: 'rmse'
  # loss: 'ideal-mag'
  # loss: 'psa'
  # loss: 'psa-bose'

seed: 10
batch_size: 16
steps: 2
epochs: 1
folder: './result'
debug: True
