default:
  - _self_
  - dset: VoiceBankDEMAND

dummy:
dset:
  wav: '/Users/seunghyunoh/workplace/study/NoiseReduction/Tiny-SpeechEnhancement/data/VoiceBankDEMAND/DS_10283_2791'
  # wav: '/home/daniel0413/workplace/project/SpeechEnhancement/TinyML/data/VoiceBankDEMAND'
  split: 0.7
  sample_rate: 16000
  segment: 1.008
  # lstm model
  # n_fft: 512
  # win_length: 512
  # hop_length: 256
  # n_feature: 257
  # n_segment: 64 # 1.008 sec in 512 window, 256 hop, sr = 16000 Hz
  # cnn model
  n_fft: 256
  win_length: 256
  hop_length: 128
  n_feature: 129 
  n_segment: 8 
  n_mels: 128
  f_min: 125
  f_max: 8000
  channels: 1
  top_db: 100
  # domain: 'time'
  domain: 'freq'
  center: True

  save_path: "./preprocess/data"
  fft_normalize: True
  time_normalize: False
  max_db: 96
  

model:
  # name: 'lstm'
  name: 'cnn'
  sample_rate: 16000
  lstm_layer: 256
  metric: 'sisdr'

optim:
  optim: 'adam'
  lr: 0.0003
  # optim: 'sgd'
  # lr: 0.001
  loss: 'mse'
  # loss: 'rmse'
  # loss: 'psa'
  clip_grad: False

seed: 10
batch_size: 512
max_batches: 1024 # ?
steps: 10
epochs: 1
folder: './result'
debug: True
